pipeline {
    agent {
        label 'slave-Ubuntu'
    }

    stages {
        stage('Checkout') {
            steps {
                // 拉取GitHub上的代码
                git url: 'git@github.com:nippon1218/mcmd.git', branch: 'main'
            }
        }
    }
}
